# .github/workflows/pr-validate.yml

name: Validate Terraform on PR

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  validate:
    uses: akumoproject/infra-shs-workflow-repo/.github/workflows/terraform-validate.yml@main
    with:
      terraform-directory: ./terraform
    secrets: inherit